### ISSUE TITLE
node index.js 失败

### ISSUE THREAD

**Issue by wilburli** [cogons/pet-chain#1]
![image](https://user-images.githubusercontent.com/13116043/35851465-176344e8-0b63-11e8-962e-98665669f94b.png)

**Comment by iinitd** [comment]
Hi, 把node升级到最新稳定版试试

**Comment by wilburli** [comment]
可以了 谢谢  哪里的价格是怎么配置的啊
![image](https://user-images.githubusercontent.com/13116043/35852534-1e8236e6-0b66-11e8-932a-6ae0c78c67cc.png)

**Comment by wilburli** [comment]
![image](https://user-images.githubusercontent.com/13116043/35852716-8c648704-0b66-11e8-8331-085871fcdc50.png)
怎么才能买到  我看只是查询   我把配置调高了

**Comment by iinitd** [comment]
Hi,
价格从左到右是普通到神话的上限，
查询之后如果没有后续操作，可能是百度服务器超时，或是百度的ocr服务超时，可采用manual模式再试试~
