### ISSUE TITLE
能查到狗的信息，但还是要手动输入验证码

### ISSUE THREAD

**Issue by zhaoyongtao** [cogons/pet-chain#4]
```
第1057次查询！
{ id: '2050376',
  petId: '1861774933050216083',
  birthType: 1,
  mutation: 0,
  generation: 0,
  rareDegree: 0,
  desc: '小莱',
  petType: 0,
  amount: '538.00',
  bgColor: '#FFCDD3',
  petUrl: 'https://blockchain-pet-online.bj.bcebos.com/PET_SVG_630a215655ee182ae335fb99e1de4778',
  validCode: '71be49b69401c45e4167e6c45dc8f79b' }
prompt: yzm:   到了此处会卡住等待输入
{ errorNo: '100',
  errorMsg: '验证码错误',
  timestamp: '2018-02-06 17:52:39',
  data: null }
```
也没有看到验证码在哪里

**Comment by iinitd** [comment]
在手动输入模式下需要查看yzm.png，然后手动输入验证码按回车，还是得靠手速~
在config.js里面可以把"manual"改成"baidu"，使用百度的ocr接口。

需要在https://ai.baidu.com/tech/ocr/general注册，并在config.js里填写相关的key。

需要说明的是百度的识别率不太高~

**Comment by hi4t** [comment]
我的一直在查，也能查到，但是没有停下卡主让输验证码。。。

**Comment by iinitd** [comment]
@zaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee 
把上下文复制出来看看呢.. 有没有报错信息

**Comment by luoo369** [comment]
第13次查询！
宠物价格为： 2018.00 ，宠物等级为： 0
你设置的对应等级购买阈值为： 2150
买得起！
{ id: '2055665',
  petId: '1861773249422987350',
  birthType: 1,
  mutation: 0,
  generation: 0,
  rareDegree: 0,
  desc: '小莱',
  petType: 0,
  amount: '2018.00',
  bgColor: '#FFFDE7',
  petUrl: 'https://blockchain-pet-online.bj.bcebos.com/PET_SVG_f0f7095c391c5f3622d29279666f1039',
  validCode: '5fbab8974229259e0e67b7fb9ffc2b83' }
第14次查询！

**Comment by luoo369** [comment]
查询好了好多次，有能买的起的，没有成功的

**Comment by iinitd** [comment]
@hub1688 请问你在config.js里填写的yzm_method是什么呢

**Comment by luoo369** [comment]
baidu

**Comment by luoo369** [comment]
yzm_method:"baidu", // "baidu" || "manual"
    threshold:[2150,2150,2150,2150,2150], // 从普通到神话的购买上限
    query_amount:1000, //查询次数
    show_affordable_message:true //显示是否买得起的信息

**Comment by iinitd** [comment]
@hub1688 百度的识别率比较低，十有八九会返回错误的验证码，所以会不断重试。可以用manual试试蛤。

**Comment by luoo369** [comment]
好我试试

**Comment by Damon-mac** [comment]
APP_ID, API_KEY 怎么填啊,是填百度的用户名和密码吗

**Comment by iinitd** [comment]
@Damon-mac 
需要在 https://ai.baidu.com/tech/ocr/general 注册文字识别的应用，在后台查看到相关的key。
如果使用manual模式则无需填写。

**Comment by Damon-mac** [comment]
还有cookie需要填吗, 填cookies里面的哪个key呀

**Comment by Damon-mac** [comment]
文字识别我注册啦, Secret Key也找到了, 就是找不到APP_ID, API_KEY这两个在哪

**Comment by iinitd** [comment]
@Damon-mac 
在chrome中打开 https://pet-chain.baidu.com/chain/dogMarket
右键 检查-network-查看queryPetsOnSale的request-复制整个cookie

管理应用里，再找找看哈，在同一页。。
