### ISSUE TITLE
cook值

### ISSUE THREAD

**Issue by wilburli** [cogons/pet-chain#6]
![image](https://user-images.githubusercontent.com/13116043/35893296-46975490-0be8-11e8-9db3-bcb70d6ec383.png)
COOKE  填的是第一个吗？

**Comment by iinitd** [comment]
在chrome中打开 https://pet-chain.baidu.com/chain/dogMarket
右键 检查-network-查看queryPetsOnSale的request header中的cookie

**Comment by wilburli** [comment]
![image](https://user-images.githubusercontent.com/13116043/35896835-1e37008e-0bf9-11e8-8942-5c66b5ad78b5.png)
是一样的啊  只是我不确定是不是这个key

**Comment by physihan** [comment]
控制台document.cookie 查一下

**Comment by iinitd** [comment]
完美
